name: Hello-Action
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - assigned
      - edited
      - opened
      - synchronize
      - reopened
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Step 1
        run: "echo hello, Github Actions!"
